"""Tests for digest narration, chunking, WAV output, and provider orchestration."""

import contextlib
import sys
import tempfile
import types
import unittest
import wave
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

from text_to_speech.audio import AudioSegment, write_wav
from text_to_speech.cli import _default_output, build_parser
from text_to_speech.digest import chunk_narration, digest_to_narration
from text_to_speech.engine import generate_audio
from text_to_speech.providers.base import SpeechProvider
from text_to_speech.providers.chatterbox_nano import ChatterboxNanoProvider
from text_to_speech.providers.kokoro import KokoroProvider


SAMPLE_DIGEST = """# Full Lab Digest — 2026-07-22 to 2026-07-28

> 2 of 5 sources had activity.

## Ariana Huffmyer Lab Notebook

### Thermal hardening trial
- **Date**: 2026-07-25
- **URL**: https://example.org/post
- **Author**: Ariana
- **Categories**: oysters, heat
- **Key finding**: *M. gigas* survived the second heat exposure at a higher rate.
- **Figures**:
  - local: figures/survival.png

---

## Cross-Notebook Patterns & Connections

### Shared Themes
- Heat stress appeared in [two notebooks](https://example.org).

## Literature Connections

### Heat stress
External literature details.

> Generated by the `full-lab-digest` skill.
"""


class TestDigestNarration(unittest.TestCase):

    def test_extracts_post_summary_without_visual_metadata(self):
        result = digest_to_narration(SAMPLE_DIGEST)
        self.assertIn("Thermal hardening trial.", result)
        self.assertIn("Author: Ariana.", result)
        self.assertIn("M. gigas survived", result)
        self.assertNotIn("https://", result)
        self.assertNotIn("figures/survival.png", result)
        self.assertNotIn("Categories", result)
        self.assertNotIn("2 of 5", result)
        self.assertNotIn("Warnings", result)

    def test_analysis_sections_are_omitted_by_default(self):
        result = digest_to_narration(SAMPLE_DIGEST)
        self.assertNotIn("Shared Themes", result)
        self.assertNotIn("External literature", result)

    def test_analysis_sections_can_be_included(self):
        result = digest_to_narration(SAMPLE_DIGEST, include_analysis=True)
        self.assertIn("Shared Themes.", result)
        self.assertIn("Heat stress appeared in two notebooks.", result)
        self.assertIn("External literature details.", result)

    def test_empty_digest_is_rejected(self):
        with self.assertRaises(ValueError):
            digest_to_narration("# Title\n\n> Metadata only")

    def test_warning_block_is_omitted(self):
        markdown = """# Digest

## Source
### Post
- **Key finding**: A real result.

**Warnings**
- Internal fetch warning that should not be spoken.
"""
        result = digest_to_narration(markdown)
        self.assertIn("A real result.", result)
        self.assertNotIn("Internal fetch warning", result)

    def test_inline_raw_url_and_parentheses_are_removed(self):
        markdown = """# Digest

## Source
### Post
- **Change this week**: Link changed to (`https://example.org/path`).
"""
        result = digest_to_narration(markdown)
        self.assertIn("Link changed to.", result)
        self.assertNotIn("https://", result)
        self.assertNotIn("(`", result)

    def test_conversational_style_adds_transitions_and_spoken_fields(self):
        result = digest_to_narration(SAMPLE_DIGEST, style="conversational")
        self.assertIn("Here's your lab notebook update.", result)
        self.assertIn("Let's start with Ariana Huffmyer Lab Notebook.", result)
        self.assertIn("First up: Thermal hardening trial.", result)
        self.assertIn("This update comes from Ariana.", result)
        self.assertIn("It was posted on July 25, 2026.", result)
        self.assertIn("Here's the main takeaway.", result)
        self.assertIn("That's the latest from the lab notebooks.", result)
        self.assertNotIn("Author:", result)
        self.assertNotIn("Key finding:", result)

    def test_conversational_style_can_include_analysis(self):
        result = digest_to_narration(
            SAMPLE_DIGEST,
            include_analysis=True,
            style="conversational",
        )
        self.assertIn("Now, let's turn to Cross-Notebook Patterns & Connections.", result)
        self.assertIn("First up: Shared Themes.", result)

    def test_conversational_style_ignores_embedded_digest_h1(self):
        markdown = """# Combined Digest

## Source
# Source Digest
### Update
- **Key finding**: Useful result.
"""
        result = digest_to_narration(markdown, style="conversational")
        self.assertEqual(result.count("Here's your lab notebook update."), 1)
        self.assertNotIn("Source Digest", result)

    def test_unknown_style_is_rejected(self):
        with self.assertRaises(ValueError):
            digest_to_narration(SAMPLE_DIGEST, style="dramatic")


class TestChunkNarration(unittest.TestCase):

    def test_chunks_stay_within_limit(self):
        text = ("One short sentence. " * 30) + "\n\n" + ("Another sentence. " * 20)
        chunks = chunk_narration(text, max_chars=100)
        self.assertGreater(len(chunks), 1)
        self.assertTrue(all(len(chunk) <= 100 for chunk in chunks))

    def test_long_unbroken_text_is_split(self):
        chunks = chunk_narration("x" * 205, max_chars=100)
        self.assertEqual([len(chunk) for chunk in chunks], [100, 100, 5])

    def test_tiny_limit_is_rejected(self):
        with self.assertRaises(ValueError):
            chunk_narration("Text.", max_chars=20)


class TestNarrationCLI(unittest.TestCase):

    def test_style_option_defaults_to_direct(self):
        args = build_parser().parse_args(["digest.md"])
        self.assertEqual(args.style, "direct")

    def test_conversational_output_does_not_overwrite_direct_output(self):
        digest = Path("digests/example.md")
        direct = _default_output(digest, "kokoro", "direct")
        conversational = _default_output(digest, "kokoro", "conversational")
        self.assertNotEqual(direct, conversational)
        self.assertEqual(conversational.name, "example-kokoro-conversational.wav")


class FakeProvider(SpeechProvider):

    def __init__(self):
        self.calls = []

    def synthesize(self, text):
        self.calls.append(text)
        # 100 samples of quiet, valid PCM at 8 kHz.
        return AudioSegment(b"\x01\x00" * 100, 8000)


class FailingProvider(SpeechProvider):

    def synthesize(self, text):
        raise RuntimeError("model failed")


class TestAudioGeneration(unittest.TestCase):

    def test_write_wav_combines_segments_and_pause(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "combined.wav"
            segments = [
                AudioSegment(b"\x01\x00" * 10, 8000),
                AudioSegment(b"\x02\x00" * 10, 8000),
            ]
            write_wav(path, segments, pause_seconds=0.01)
            with wave.open(str(path), "rb") as audio:
                self.assertEqual(audio.getnchannels(), 1)
                self.assertEqual(audio.getsampwidth(), 2)
                self.assertEqual(audio.getframerate(), 8000)
                self.assertEqual(audio.getnframes(), 10 + 80 + 10)

    def test_engine_calls_provider_once_per_chunk(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "narration.wav"
            provider = FakeProvider()
            count = generate_audio(
                "First sentence. " * 30,
                path,
                provider,
                chunk_chars=100,
                pause_seconds=0,
            )
            self.assertEqual(count, len(provider.calls))
            self.assertGreater(count, 1)
            self.assertTrue(path.is_file())

    def test_failed_generation_does_not_leave_partial_output(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "narration.wav"
            with self.assertRaises(RuntimeError):
                generate_audio("A valid sentence.", path, FailingProvider())
            self.assertFalse(path.exists())
            self.assertEqual(list(Path(directory).glob(".digest-audio-*")), [])

    def test_empty_segment_list_is_rejected(self):
        with tempfile.TemporaryDirectory() as directory:
            with self.assertRaises(ValueError):
                write_wav(Path(directory) / "empty.wav", [])


class TestProviderAdapters(unittest.TestCase):

    def test_kokoro_passes_voice_language_and_speed(self):
        calls = {}

        class FakePipeline:

            def __init__(self, lang_code, repo_id):
                calls["language"] = lang_code
                calls["repo_id"] = repo_id

            def __call__(self, text, **options):
                calls["text"] = text
                calls.update(options)
                return [("words", "phonemes", object())]

        module = types.ModuleType("kokoro")
        module.KPipeline = FakePipeline
        expected = AudioSegment(b"\x01\x00" * 10, 24000)
        with patch.dict(sys.modules, {"kokoro": module}):
            with patch(
                "text_to_speech.providers.kokoro.samples_to_segment",
                return_value=expected,
            ):
                provider = KokoroProvider(voice="af_test", language="a", speed=1.2)
                result = provider.synthesize("Notebook result.")

        self.assertEqual(result, expected)
        self.assertEqual(calls["language"], "a")
        # The repo_id is pinned so the pipeline cannot silently resolve elsewhere.
        self.assertEqual(calls["repo_id"], KokoroProvider.REPO_ID)
        self.assertEqual(calls["voice"], "af_test")
        self.assertEqual(calls["speed"], 1.2)
        self.assertEqual(calls["text"], "Notebook result.")

    def test_chatterbox_loads_nano_and_uses_reference_clip(self):
        calls = {}

        class FakeModel:
            sr = 24000

            @classmethod
            def from_pretrained(cls, **options):
                calls["load"] = options
                return cls()

            def generate(self, text, **options):
                calls["text"] = text
                calls["generate"] = options
                return object()

        torch = types.ModuleType("torch")
        torch.cuda = SimpleNamespace(is_available=lambda: False)
        torch.backends = SimpleNamespace(
            mps=SimpleNamespace(is_available=lambda: False)
        )
        torch.inference_mode = contextlib.nullcontext

        chatterbox = types.ModuleType("chatterbox")
        chatterbox.__path__ = []
        turbo = types.ModuleType("chatterbox.tts_turbo")
        turbo.ChatterboxTurboTTS = FakeModel

        expected = AudioSegment(b"\x02\x00" * 10, 24000)
        with tempfile.NamedTemporaryFile(suffix=".wav") as voice:
            with patch.dict(
                sys.modules,
                {
                    "torch": torch,
                    "chatterbox": chatterbox,
                    "chatterbox.tts_turbo": turbo,
                },
            ):
                with patch(
                    "text_to_speech.providers.chatterbox_nano.samples_to_segment",
                    return_value=expected,
                ):
                    provider = ChatterboxNanoProvider(
                        device="auto",
                        voice_sample=voice.name,
                    )
                    result = provider.synthesize("Notebook result.")

        self.assertEqual(result, expected)
        self.assertEqual(calls["load"], {"device": "cpu", "nano": True})
        self.assertEqual(calls["text"], "Notebook result.")
        self.assertEqual(calls["generate"], {"audio_prompt_path": voice.name})

    def test_chatterbox_rejects_missing_voice_sample_before_loading(self):
        with self.assertRaises(ValueError):
            ChatterboxNanoProvider(voice_sample="/definitely/missing/voice.wav")


if __name__ == "__main__":
    unittest.main()
